sonar.projectKey=my-mdm-app
sonar.projectName=MDM Application
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9900

sonar.sources=src,api
sonar.tests=src/__tests__,api/tests
sonar.exclusions=src/__tests__/**,api/tests/**,node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.python.coverage.reportPaths=coverage.xml

sonar.language=ts,py
sonar.sourceEncoding=UTF-8
